### ISSUE TITLE
Timer metrics report with meaningless metric names

### ISSUE THREAD

**Issue by dmaze** [wavefrontHQ/nodejs-metrics-wavefront#22]
We received a complaint that our Wavefront instance was receiving meaningless metrics that seemed to have a timestamp as the principal part of the metric name, for example `1586196817.602..p95`.  The only meter type our code uses in this particular application is a `Timer`.

From code inspection, it looks like the reporting for a `Timer` reports its summary statistics, and then delegates to report the histogram metrics.  When that delegation happens [it looks like it doesn't pass down the `metricName`](https://github.com/wavefrontHQ/nodejs-metrics-wavefront/blob/master/lib/wavefront-metrics-formatter.js#L37).

If this is correct then this should reproduce with as little as (minimally tested):

```js
const { Registry, Timer, WavefrontProxyReporter } = require('wavefrontmetrics');
const registry = new Registry();
registry.addMetric('foo.bar', new Timer());
const reporter = new WavefrontProxyReporter(registry, '', 'localhost');
reporter.start(1000);
setTimeout(function() {
  reporter.stop();
}, 2000);
```

**Comment by yzheqing** [comment]
resolved in the latest release
